### ISSUE TITLE
ptyprocess 0.5.1 and 0.5.2 appear to be missing the setup.py file.

### ISSUE THREAD

**Issue by bignordique** [pexpect/ptyprocess#44]

**Comment by takluyver** [comment]
If you get the [tarball from PyPI](https://pypi.python.org/packages/51/83/5d07dc35534640b06f9d9f1a1d2bc2513fb9cc7595a1b0e28ae5477056ce/ptyprocess-0.5.2.tar.gz#md5=d3b8febae1b8c53b054bd818d0bb8665), it contains a setup.py file. There isn't one in the git repository because it's packaged using Flit, which doesn't need one. The one in the tarball is autogenerated.

**Comment by bignordique** [comment]
Don't know much about Python distro tools.

I'm including ptyprocess in a Yocto build.  Yocto does require setup.py.
